# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import elexonpy
from elexonpy.models.insights_api_models_responses_misc_system_frequency import InsightsApiModelsResponsesMiscSystemFrequency  # noqa: E501
from elexonpy.rest import ApiException


class TestInsightsApiModelsResponsesMiscSystemFrequency(unittest.TestCase):
    """InsightsApiModelsResponsesMiscSystemFrequency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsightsApiModelsResponsesMiscSystemFrequency(self):
        """Test InsightsApiModelsResponsesMiscSystemFrequency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = elexonpy.models.insights_api_models_responses_misc_system_frequency.InsightsApiModelsResponsesMiscSystemFrequency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
