# coding: utf-8

"""
    Insights API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.legacy_api import LegacyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLegacyApi(unittest.TestCase):
    """LegacyApi unit test stubs"""

    def setUp(self):
        self.api = LegacyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_interop_messagedetailretrieval_messageid_messageid(self):
        """Test case for get_interop_messagedetailretrieval_messageid_messageid

        This endpoint is obsolete, and this location may be removed with no further notice. Use /remit/* or /datasets/REMIT endpoints instead.  # noqa: E501
        """
        pass

    def test_get_interop_messagelistretrieval_eventstart_eventstart_eventend_eventend(self):
        """Test case for get_interop_messagelistretrieval_eventstart_eventstart_eventend_eventend

        This endpoint is obsolete, and this location may be removed with no further notice. Use /remit/* or /datasets/REMIT endpoints instead.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
