# coding: utf-8

"""
    Insights API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""



import unittest

import elexonpy
from elexonpy.api.balancing_services_adjustment___disaggregated_api import BalancingServicesAdjustmentDisaggregatedApi  # noqa: E501
from elexonpy.rest import ApiException


class TestBalancingServicesAdjustmentDisaggregatedApi(unittest.TestCase):
    """BalancingServicesAdjustmentDisaggregatedApi unit test stubs"""

    def setUp(self):
        self.api = BalancingServicesAdjustmentDisaggregatedApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_balancing_nonbm_disbsad_details_settlementdate_settlementdate_settlement(self):
        """Test case for get_balancing_nonbm_disbsad_details_settlementdate_settlementdate_settlement

        Disaggregated balancing services adjustment per settlement period (DISBSAD)  # noqa: E501
        """
        pass

    def test_get_balancing_nonbm_disbsad_summary_from_from_to_to(self):
        """Test case for get_balancing_nonbm_disbsad_summary_from_from_to_to

        Disaggregated balancing services adjustment time series (DISBSAD)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
