# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.insights_api_models_responses_misc_temperature_data import InsightsApiModelsResponsesMiscTemperatureData  # noqa: E501
from swagger_client.rest import ApiException


class TestInsightsApiModelsResponsesMiscTemperatureData(unittest.TestCase):
    """InsightsApiModelsResponsesMiscTemperatureData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsightsApiModelsResponsesMiscTemperatureData(self):
        """Test InsightsApiModelsResponsesMiscTemperatureData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.insights_api_models_responses_misc_temperature_data.InsightsApiModelsResponsesMiscTemperatureData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
