# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import elexonpy
from elexonpy.api.so_so_prices_api import SOSOPricesApi  # noqa: E501
from elexonpy.rest import ApiException


class TestSOSOPricesApi(unittest.TestCase):
    """SOSOPricesApi unit test stubs"""

    def setUp(self):
        self.api = SOSOPricesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_soso_prices_get(self):
        """Test case for soso_prices_get

        SO-SO prices (SOSO)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
