# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.insights_api_models_responses_demand_outturn_indicative_demand_peak import InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak  # noqa: E501
from swagger_client.rest import ApiException


class TestInsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak(unittest.TestCase):
    """InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak(self):
        """Test InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.insights_api_models_responses_demand_outturn_indicative_demand_peak.InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
