# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import elexonpy
from elexonpy.models.insights_api_models_responses_balancing_credit_default_notice_response import InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse  # noqa: E501
from elexonpy.rest import ApiException


class TestInsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse(unittest.TestCase):
    """InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse(self):
        """Test InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = elexonpy.models.insights_api_models_responses_balancing_credit_default_notice_response.InsightsApiModelsResponsesBalancingCreditDefaultNoticeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
