# coding: utf-8

"""
    Insights API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.demand_forecast_api import DemandForecastApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDemandForecastApi(unittest.TestCase):
    """DemandForecastApi unit test stubs"""

    def setUp(self):
        self.api = DemandForecastApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_forecast_demand_daily(self):
        """Test case for get_forecast_demand_daily

        Fourteen day demand forecast (NDFD, TSDFD)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_daily_evolution_forecastdate_forecastdate(self):
        """Test case for get_forecast_demand_daily_evolution_forecastdate_forecastdate

        Evolution of the fourteen-day demand forecast over time (NDFD, TSDFD)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_daily_history_publishtime_publishtime(self):
        """Test case for get_forecast_demand_daily_history_publishtime_publishtime

        History of the fourteen-day demand forecast (NDFD, TSDFD)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead(self):
        """Test case for get_forecast_demand_day_ahead

        Day-ahead demand forecast (NDF, TSDF)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_earliest_from_from_to_to(self):
        """Test case for get_forecast_demand_day_ahead_earliest_from_from_to_to

        Historic view of the earliest forecasted demand (NDF, TSDF)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_earliest_stream_from_from_to_to(self):
        """Test case for get_forecast_demand_day_ahead_earliest_stream_from_from_to_to

        Historic view of the earliest forecasted demand (NDF, TSDF) stream  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_evolution_settlementdate_settlementdate_settle(self):
        """Test case for get_forecast_demand_day_ahead_evolution_settlementdate_settlementdate_settle

        Evolution of the day-ahead demand forecast over time (NDF, TSDF)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_history_publishtime_publishtime(self):
        """Test case for get_forecast_demand_day_ahead_history_publishtime_publishtime

        History of the day-ahead demand forecast (NDF, TSDF)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_latest_from_from_to_to(self):
        """Test case for get_forecast_demand_day_ahead_latest_from_from_to_to

        Historic view of the latest forecasted demand (NDF, TSDF)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_latest_stream_from_from_to_to(self):
        """Test case for get_forecast_demand_day_ahead_latest_stream_from_from_to_to

        Historic view of the latest forecasted demand (NDF, TSDF) stream  # noqa: E501
        """
        pass

    def test_get_forecast_demand_day_ahead_peak(self):
        """Test case for get_forecast_demand_day_ahead_peak

        Peak forecasted demand per day (TSDF)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_total_day_ahead_from_from_to_to(self):
        """Test case for get_forecast_demand_total_day_ahead_from_from_to_to

        Day-ahead total load forecast (DATL/B0620)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_total_week_ahead_from_from_to_to(self):
        """Test case for get_forecast_demand_total_week_ahead_from_from_to_to

        Week-ahead total load forecast (WATL/B0630)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_total_week_ahead_latest(self):
        """Test case for get_forecast_demand_total_week_ahead_latest

        Latest week-ahead total load forecast (WATL/B0630)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_weekly(self):
        """Test case for get_forecast_demand_weekly

        One-year demand forecast (NDFW, TSDFW)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_weekly_evolution_forecastyear_forecastyear_forecastweek(self):
        """Test case for get_forecast_demand_weekly_evolution_forecastyear_forecastyear_forecastweek

        Evolution of the one-year demand forecast over time  (NDFW, TSDFW)  # noqa: E501
        """
        pass

    def test_get_forecast_demand_weekly_history_publishtime_publishtime(self):
        """Test case for get_forecast_demand_weekly_history_publishtime_publishtime

        History of the one-year demand forecast (NDFW, TSDFW)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
