# coding: utf-8

"""
    Insights API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""



import unittest

import elexonpy
from elexonpy.api.surplus_forecast_api import SurplusForecastApi  # noqa: E501
from elexonpy.rest import ApiException


class TestSurplusForecastApi(unittest.TestCase):
    """SurplusForecastApi unit test stubs"""

    def setUp(self):
        self.api = SurplusForecastApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_forecast_surplus_daily(self):
        """Test case for get_forecast_surplus_daily

        Daily surplus forecast (OCNMFD)  # noqa: E501
        """
        pass

    def test_get_forecast_surplus_daily_evolution_forecastdate_forecastdate(self):
        """Test case for get_forecast_surplus_daily_evolution_forecastdate_forecastdate

        Evolution daily surplus forecast (OCNMFD)  # noqa: E501
        """
        pass

    def test_get_forecast_surplus_daily_history_publishtime_publishtime(self):
        """Test case for get_forecast_surplus_daily_history_publishtime_publishtime

        Historical daily surplus forecast (OCNMFD)  # noqa: E501
        """
        pass

    def test_get_forecast_surplus_weekly(self):
        """Test case for get_forecast_surplus_weekly

        Weekly surplus forecast (OCNMFW, OCNMF3Y)  # noqa: E501
        """
        pass

    def test_get_forecast_surplus_weekly_evolution_year_year_week_week(self):
        """Test case for get_forecast_surplus_weekly_evolution_year_year_week_week

        Evolution weekly surplus forecast (OCNMFW, OCNMF3Y)  # noqa: E501
        """
        pass

    def test_get_forecast_surplus_weekly_history_publishtime_publishtime(self):
        """Test case for get_forecast_surplus_weekly_history_publishtime_publishtime

        Historical weekly surplus forecast (OCNMFW, OCNMF3Y)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
