# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import elexonpy
from elexonpy.api.credit_default_notice_api import CreditDefaultNoticeApi  # noqa: E501
from elexonpy.rest import ApiException


class TestCreditDefaultNoticeApi(unittest.TestCase):
    """CreditDefaultNoticeApi unit test stubs"""

    def setUp(self):
        self.api = CreditDefaultNoticeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_c_dn_get(self):
        """Test case for c_dn_get

        [DEPRECATED] Credit default notices (CDN)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
