# coding: utf-8

"""
    Insights API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.remit_api import RemitApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRemitApi(unittest.TestCase):
    """RemitApi unit test stubs"""

    def setUp(self):
        self.api = RemitApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_remit_list_by_event_from_from_to_to(self):
        """Test case for get_remit_list_by_event_from_from_to_to

        List messages by event time  # noqa: E501
        """
        pass

    def test_get_remit_list_by_event_stream_from_from_to_to(self):
        """Test case for get_remit_list_by_event_stream_from_from_to_to

        List messages by event time (stream)  # noqa: E501
        """
        pass

    def test_get_remit_list_by_publish_from_from_to_to(self):
        """Test case for get_remit_list_by_publish_from_from_to_to

        List messages by publish time  # noqa: E501
        """
        pass

    def test_get_remit_list_by_publish_stream_from_from_to_to(self):
        """Test case for get_remit_list_by_publish_stream_from_from_to_to

        List messages by publish time (stream)  # noqa: E501
        """
        pass

    def test_get_remit_messageid(self):
        """Test case for get_remit_messageid

        Fetch message details by ID  # noqa: E501
        """
        pass

    def test_get_remit_messageid_messageid(self):
        """Test case for get_remit_messageid_messageid

        Bulk fetch message details by IDs  # noqa: E501
        """
        pass

    def test_get_remit_revisions(self):
        """Test case for get_remit_revisions

        List all message revisions  # noqa: E501
        """
        pass

    def test_get_remit_search_mrid_mrid(self):
        """Test case for get_remit_search_mrid_mrid

        Fetch message details by mRID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
