# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'settlement_date': 'date',
        'settlement_period': 'int',
        'half_hour_end_time': 'datetime',
        'demand': 'float',
        'settlement_run_type': 'str'
    }

    attribute_map = {
        'settlement_date': 'settlementDate',
        'settlement_period': 'settlementPeriod',
        'half_hour_end_time': 'halfHourEndTime',
        'demand': 'demand',
        'settlement_run_type': 'settlementRunType'
    }

    def __init__(self, settlement_date=None, settlement_period=None, half_hour_end_time=None, demand=None, settlement_run_type=None):  # noqa: E501
        """InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak - a model defined in Swagger"""  # noqa: E501
        self._settlement_date = None
        self._settlement_period = None
        self._half_hour_end_time = None
        self._demand = None
        self._settlement_run_type = None
        self.discriminator = None
        if settlement_date is not None:
            self.settlement_date = settlement_date
        if settlement_period is not None:
            self.settlement_period = settlement_period
        if half_hour_end_time is not None:
            self.half_hour_end_time = half_hour_end_time
        if demand is not None:
            self.demand = demand
        if settlement_run_type is not None:
            self.settlement_run_type = settlement_run_type

    @property
    def settlement_date(self):
        """Gets the settlement_date of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501


        :return: The settlement_date of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :rtype: date
        """
        return self._settlement_date

    @settlement_date.setter
    def settlement_date(self, settlement_date):
        """Sets the settlement_date of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.


        :param settlement_date: The settlement_date of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :type: date
        """

        self._settlement_date = settlement_date

    @property
    def settlement_period(self):
        """Gets the settlement_period of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501


        :return: The settlement_period of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :rtype: int
        """
        return self._settlement_period

    @settlement_period.setter
    def settlement_period(self, settlement_period):
        """Sets the settlement_period of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.


        :param settlement_period: The settlement_period of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :type: int
        """

        self._settlement_period = settlement_period

    @property
    def half_hour_end_time(self):
        """Gets the half_hour_end_time of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501


        :return: The half_hour_end_time of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :rtype: datetime
        """
        return self._half_hour_end_time

    @half_hour_end_time.setter
    def half_hour_end_time(self, half_hour_end_time):
        """Sets the half_hour_end_time of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.


        :param half_hour_end_time: The half_hour_end_time of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :type: datetime
        """

        self._half_hour_end_time = half_hour_end_time

    @property
    def demand(self):
        """Gets the demand of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501


        :return: The demand of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :rtype: float
        """
        return self._demand

    @demand.setter
    def demand(self, demand):
        """Sets the demand of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.


        :param demand: The demand of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :type: float
        """

        self._demand = demand

    @property
    def settlement_run_type(self):
        """Gets the settlement_run_type of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501


        :return: The settlement_run_type of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :rtype: str
        """
        return self._settlement_run_type

    @settlement_run_type.setter
    def settlement_run_type(self, settlement_run_type):
        """Sets the settlement_run_type of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.


        :param settlement_run_type: The settlement_run_type of this InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak.  # noqa: E501
        :type: str
        """

        self._settlement_run_type = settlement_run_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InsightsApiModelsResponsesDemandOutturnIndicativeDemandPeak):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
