# coding: utf-8

"""
    Insights.Api

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InsightsApiModelsResponsesReferenceInterconnectorData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interconnector_id': 'str',
        'interconnector_name': 'str',
        'interconnector_bidding_zone': 'str'
    }

    attribute_map = {
        'interconnector_id': 'interconnectorId',
        'interconnector_name': 'interconnectorName',
        'interconnector_bidding_zone': 'interconnectorBiddingZone'
    }

    def __init__(self, interconnector_id=None, interconnector_name=None, interconnector_bidding_zone=None):  # noqa: E501
        """InsightsApiModelsResponsesReferenceInterconnectorData - a model defined in Swagger"""  # noqa: E501
        self._interconnector_id = None
        self._interconnector_name = None
        self._interconnector_bidding_zone = None
        self.discriminator = None
        if interconnector_id is not None:
            self.interconnector_id = interconnector_id
        if interconnector_name is not None:
            self.interconnector_name = interconnector_name
        if interconnector_bidding_zone is not None:
            self.interconnector_bidding_zone = interconnector_bidding_zone

    @property
    def interconnector_id(self):
        """Gets the interconnector_id of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501


        :return: The interconnector_id of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501
        :rtype: str
        """
        return self._interconnector_id

    @interconnector_id.setter
    def interconnector_id(self, interconnector_id):
        """Sets the interconnector_id of this InsightsApiModelsResponsesReferenceInterconnectorData.


        :param interconnector_id: The interconnector_id of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501
        :type: str
        """

        self._interconnector_id = interconnector_id

    @property
    def interconnector_name(self):
        """Gets the interconnector_name of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501


        :return: The interconnector_name of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501
        :rtype: str
        """
        return self._interconnector_name

    @interconnector_name.setter
    def interconnector_name(self, interconnector_name):
        """Sets the interconnector_name of this InsightsApiModelsResponsesReferenceInterconnectorData.


        :param interconnector_name: The interconnector_name of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501
        :type: str
        """

        self._interconnector_name = interconnector_name

    @property
    def interconnector_bidding_zone(self):
        """Gets the interconnector_bidding_zone of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501


        :return: The interconnector_bidding_zone of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501
        :rtype: str
        """
        return self._interconnector_bidding_zone

    @interconnector_bidding_zone.setter
    def interconnector_bidding_zone(self, interconnector_bidding_zone):
        """Sets the interconnector_bidding_zone of this InsightsApiModelsResponsesReferenceInterconnectorData.


        :param interconnector_bidding_zone: The interconnector_bidding_zone of this InsightsApiModelsResponsesReferenceInterconnectorData.  # noqa: E501
        :type: str
        """

        self._interconnector_bidding_zone = interconnector_bidding_zone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InsightsApiModelsResponsesReferenceInterconnectorData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InsightsApiModelsResponsesReferenceInterconnectorData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
